### ISSUE TITLE
Async Zarr blog date

### ISSUE THREAD

**Issue by jakirkham** [martindurant/martindurant.github.io#1]
This says `2022-12-03`, but maybe it should be `2022-12-02`?

https://github.com/martindurant/martindurant.github.io/blob/18762d36974bf60e9a953629f88c26fa854f7b0b/Martin%20Durant/content/blog/async-zarr/contents.lr#L5

**Comment by martindurant** [comment]
I haven't advertised it yet, incase anyone in the zarr group wants to comment.

**Comment by jakirkham** [comment]
Ah ok. So this is the date it official ships?

**Comment by martindurant** [comment]
We'll see. I conservatively tend to put the date a day or so in the future, just in case, but it can always be edited.
